apiVersion: apps/v1
kind: Deployment
metadata:
  name: componentes-ui
  labels:
    app: componentes-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: componentes-ui
  template:
    metadata:
      labels:
        app: componentes-ui
    spec:
      containers:
      - name: componentes-ui
        image: andreshts/componentes-ui:latest
        ports:
        - containerPort: 80
