import { RouteInfo } from "./header.metadata";

export const AdminRoutes: RouteInfo[] = [
  {
    path: '/admin/home-admin',
    title: 'Inicio',
    icon: 'bi-house-door',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/products',
    title: 'Productos',
    icon: 'bi-box-seam',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/invoices',
    title: 'Facturas',
    icon: 'bi-file-earmark-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/orders',
    title: 'Pedidos',
    icon: 'bi-basket',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/users',
    title: 'Usuarios',
    icon: 'bi-people',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/admin/settings',
    title: 'Configuración',
    icon: 'bi-gear',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/admin/logs',
        title: 'Logs',
        icon: 'bi-graph-up',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
];
